version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hospital_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db      # Maps your host data folder
      - ./data:/app/data  # Maps your raw text reports
    env_file:
      - .env              # Loads your Groq API Key
    networks:
      - ai_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital_frontend
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - ai_network


networks:
  ai_network:
    driver: bridge